### ISSUE TITLE
Изменение url при подвязке к определенной странице

### ISSUE THREAD

**Issue by MakarVG** [Joomla-Ukraine/JUMultiThumb#4]
ВЫлез другой бок — при подвязке к странице модуль начинает генерировать ссылки с путем этой страницы:
Модуль привязан к странице http://krakow.net.ua/novosti.
В результате все страницы имеют url не 
http://krakow.net.ua/8-novosti/65-festival-polskoji-kulturii, 
а http://krakow.net.ua/novosti/8-novosti/65-festival-polskoji-kulturii
![image](https://user-images.githubusercontent.com/30416611/28580111-3fab231c-7167-11e7-8ce9-fd3a9b8298c7.png)

**Comment by denysdesign** [comment]
@Makar91 модуль берет ссылки с выбранного вами формата отображения материалов. В данном случаи вам нужно просто корректно настроить пункты меню для всех разделов сайта.
